### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by alvin0319** [organization/Kookie#2]
# General
* [ ] JVM 인자로 플러그인 경로, 데이터 경로 설정 가능하게 하기. (Allow users to set the path of data folder and plugin path)
* [ ] 서버사이드 블럭 파괴 및 서버사이드 움직임 처리 구현. (Implement server-side block breaking and movement)

# Packet

- [ ] Force packets to use its constructor instead of `Packet.create()` method

**Comment by brokiem** [comment]
what?

**Comment by alvin0319** [comment]
@brokiem translated ^_^

**Comment by RealBJsingh** [comment]
:thonk:
